self.addEventListener("install",e=>{
  self.skipWaiting();
  e.waitUntil(
    caches.open("codenote-v1").then(c=>
      c.addAll(["/Note/","/Note/index.html","/Note/manifest.json"])
    )
  );
});
self.addEventListener("fetch",e=>{
  e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)));
});
